version: '3.9'

services:
  web:
    image: host-trainee
    ports:
      - "9091:9091"
    restart: always
    links:
      - core
    environment:
      - "spring.profiles.active=prod"

  core:
    image: host-trainee
    ports:
      - "9092:9092"
    restart: always
    environment:
      - "spring.profiles.active=prod"

  common:
    image: host-trainee
    ports:
      - "9093:9093"
    restart: always
    environment:
      - "spring.profiles.active=prod"

  application:
    image: host-trainee
    ports:
      - "9094:9094"
    restart: always
    links:
      - web
    environment:
      - "spring.profiles.active=prod"