#SERVER
server:
  port: 9090

#DB
spring.datasource:
  db_ip: ${DB_IP:localhost}
  db_port: ${DB_PORT:5432}
  db_name: ${DB_NAME:postgres}
  db_schema: ${DB_SCHEMA:timetable}
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://${spring.datasource.db_ip}:${spring.datasource.db_port}/${spring.datasource.db_name}?currentSchema=${spring.datasource.db_schema}
  username: ${POSTGRES_USERNAME:postgres}
  password: ${POSTGRES_PASSWORD:11gamane}

#SECURITY
security:
  oauth2:
    client:
      clientId: 27689494110-9atu1pd9er9brgeiemhgisu3pv616cjd.apps.googleusercontent.com
      clientSecret: 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
      clientAuthenticationScheme: form
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      scope: openid,email,profile
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
      preferTokenInfo: 'true'

#JPA
spring.jpa:
  show-sql: true
  hibernate:
    ddl-auto: none
  properties:
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.enable_lazy_load_no_trans: true
    hibernate.event:
      merge:
        entity_copy_observer: allow


#PAGE
spring.data.web:
  pageable:
    default-page-size: 10
    max-page-size: 2000
    one-indexed-parameters: true
    prefix:
    qualifier-delimiter:
    size-parameter: size
    page-parameter: page

spring:
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:5MB}
      max-request-size: ${MAX_REQUEST_SIZE:20MB}
  main:
    allow-bean-definition-overriding: true


#FILE
com.vhry:
  file:
    path: ${FILE_PATH:timetable.files}

