#SERVER
server:
  port: 9090

#DB
spring.datasource:
  platform: postgres
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/postgres
  username: postgres
  password: admin

#JPA
spring.jpa:
  show-sql: true
  hibernate:
    ddl-auto: none
  properties:
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect


spring.data.web:
  pageable:
    default-page-size: 10
    max-page-size: 2000
    one-indexed-parameters: true
    prefix:
    qualifier-delimiter:
    size-parameter: size
    page-parameter: page