#SERVER
server:
  port: 9090

#DB
spring.datasource:
  db_ip: ${DB_IP:localhost}
  db_port: ${DB_PORT:5432}
  db_name: ${DB_NAME:postgres}
  platform: postgres
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://${spring.datasource.db_ip}:${spring.datasource.db_port}/${spring.datasource.db_name}
  username: ${POSTGRES_USERNAME}
  password: ${POSTGRES_PASSWORD}


#JPA
spring.jpa:
  show-sql: true
  hibernate:
    ddl-auto: none
  properties:
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect


#PAGEABLE
spring.data.web:
  pageable:
    default-page-size: 10
    max-page-size: 2000
    one-indexed-parameters: true
    prefix:
    qualifier-delimiter:
    size-parameter: size
    page-parameter: page


#MULTIPART
spring:
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:5MB}
      max-request-size: ${MAX_REQUEST_SIZE:20MB}
  main:
    allow-bean-definition-overriding: true


#FILE
com.epolsoft:
  file:
    path: ${FILE_PATH}