export default {
  HERO: "HERO_",
  HEROES: "HEROES_",
  DICTIONARIES: "DICTIONARIES_",

  MATCH: "MATCH_",
  MATCHES: "MATCHES_",

  CLASSES: "CLASSES_",
  USER: "USER_",
  FACULTIES: "FACULTIES_"
};